version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-https://localhost:8087/my_budget}
        - VITE_WS_URL=${VITE_WS_URL:-wss://localhost:8087/my_budget}
    ports:
      - "3000:80"