services:
  frontend:
    build:
      context: .
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:8087/my_budget}
        - VITE_WS_URL=${VITE_WS_URL:-ws://localhost:8087/my_budget/ws}
    ports:
      - "3000:3000"